const defaults=[{name:'Needs & bills',percent:50,color:'#b99655'},{name:'Everyday spending',percent:20,color:'#71869a'},{name:'Savings',percent:15,color:'#668b7b'},{name:'Investing',percent:10,color:'#827393'},{name:'Giving',percent:5,color:'#8f695e'}];
let categories=JSON.parse(localStorage.getItem('citadel-categories')||localStorage.getItem('quota-categories')||localStorage.getItem('sprout-categories'))||defaults;
let history=JSON.parse(localStorage.getItem('citadel-history')||localStorage.getItem('quota-history')||localStorage.getItem('sprout-history'))||[];
let bills=JSON.parse(localStorage.getItem('citadel-bills')||localStorage.getItem('quota-bills'))||[];
let manualAllocation=localStorage.getItem('citadel-manual-allocation')==='true';
const $=s=>document.querySelector(s),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v||0);
const typeLabels={essential:'Essential',debt:'Debt minimum',standard:'Standard',optional:'Optional'},priorityColors={essential:'#d3ad64',debt:'#b58069',standard:'#71869a',optional:'#5d626a'};
function save(){localStorage.setItem('citadel-categories',JSON.stringify(categories));localStorage.setItem('citadel-history',JSON.stringify(history));localStorage.setItem('citadel-bills',JSON.stringify(bills));localStorage.setItem('citadel-manual-allocation',String(manualAllocation))}
function dueDateFor(day,reference){const d=new Date(reference+'T12:00:00'),c=new Date(d.getFullYear(),d.getMonth(),Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()),12);if(c<d)c.setMonth(c.getMonth()+1);c.setDate(Math.min(day,new Date(c.getFullYear(),c.getMonth()+1,0).getDate()));return c}
function occurrencesFor(b,pay,next){if(b.frequency!=='biweekly')return[{...b,date:dueDateFor(b.dueDay,pay)}];const start=new Date(pay+'T12:00:00'),end=new Date(next),anchor=new Date(b.anchorDate+'T12:00:00');if(Number.isNaN(anchor.getTime()))return[];const cycle=14*86400000;let date=new Date(anchor);if(date<start)date=new Date(anchor.getTime()+Math.ceil((start-anchor)/cycle)*cycle);const out=[];while(date<=end){out.push({...b,date:new Date(date)});date=new Date(date.getTime()+cycle)}return out}
function analyze(amount){
 const pay=$('#payDate').value,next=new Date($('#nextPayDate').value+'T23:59:59');
 const due=bills.flatMap(b=>occurrencesFor(b,pay,next)).filter(b=>b.date<=next).sort((a,b)=>a.date-b.date);
 const required=due.reduce((s,b)=>s+b.amount,0),allocations=categories.map(c=>({...c,amount:amount*c.percent/100,adjusted:false}));
 const ni=Math.max(0,allocations.findIndex(c=>/need|bill/i.test(c.name))),extra=Math.max(0,Math.min(amount,required)-(allocations[ni]?.amount||0));
 if(extra&&!manualAllocation&&allocations[ni]){allocations[ni].amount+=extra;allocations[ni].adjusted=true;let left=extra;[/giv/i,/every|spend/i,/invest/i,/sav/i].forEach(p=>{const item=allocations.find(c=>p.test(c.name));if(!item||left<=0)return;const cut=Math.min(item.amount,left);item.amount-=cut;item.adjusted=cut>0;left-=cut})}
 const over=allocations.reduce((s,c)=>s+c.amount,0)-amount;if(over>0&&!manualAllocation&&allocations[ni])allocations[ni].amount-=over;
 const shortfall=Math.max(0,required-amount),essential=due.filter(b=>b.type==='essential').reduce((s,b)=>s+b.amount,0),reasons=[];
 reasons.push(due.length?`${due.length} bill${due.length===1?'':'s'} totaling ${money(required)} ${due.length===1?'is':'are'} due before your next deposit.`:'No bills fall before the next payday, so your baseline strategy remains active.');
 if(essential)reasons.push(`${money(essential)} in essential obligations receives first priority to reduce housing, utility, or coverage risk.`);
 if(extra&&!manualAllocation)reasons.push(`${money(extra)} was redirected from lower-consequence categories to fund upcoming obligations.`);
 if(manualAllocation)reasons.push('Manual allocation is active. Your percentages will stay fixed until you generate a new smart plan.');
 if(shortfall)reasons.push(`Critical shortfall: this paycheck is ${money(shortfall)} below bills due. Defer optional bills or use funds from another account.`);
 return{allocations,due,required,shortfall,reasons};
}
function render(){
 const amount=Number($('#paycheck').value)||0,a=analyze(amount),grid=$('#allocationGrid');grid.innerHTML='';
 const payHeadline=$('#payHeadline');if(payHeadline)payHeadline.textContent=money(amount);
 a.allocations.forEach((c,i)=>{const card=$('#allocationTemplate').content.cloneNode(true),root=card.querySelector('.allocation-card');root.style.setProperty('--accent',c.color);if(c.adjusted)root.classList.add('adjusted');card.querySelector('.category-name').value=c.name;card.querySelector('.money').textContent=money(c.amount);card.querySelector('.percentage').value=amount?Math.round(c.amount/amount*1000)/10:c.percent;card.querySelector('.bar i').style.width=`${amount?Math.min(c.amount/amount*100,100):0}%`;card.querySelector('.category-name').addEventListener('change',e=>update(i,'name',e.target.value));card.querySelector('.percentage').addEventListener('change',e=>update(i,'percent',Math.max(0,Number(e.target.value)||0)));card.querySelector('.minus').addEventListener('click',()=>update(i,'percent',Math.max(0,categories[i].percent-1)));card.querySelector('.plus').addEventListener('click',()=>update(i,'percent',categories[i].percent+1));card.querySelector('.remove').addEventListener('click',()=>{categories.splice(i,1);save();render()});grid.append(card)});
 const allocated=a.allocations.reduce((s,c)=>s+c.amount,0),pct=amount?Math.round(allocated/amount*100):0;$('#percentTotal').textContent=pct;$('.total-pill').classList.toggle('invalid',pct!==100);$('#allocatedTotal').textContent=money(allocated);$('#paycheckTotal').textContent=money(amount);$('#yearlySavings').textContent=money(a.allocations.filter(c=>/sav|invest/i.test(c.name)).reduce((s,c)=>s+c.amount,0)*12).replace('.00','');$('#advisorTitle').textContent=manualAllocation?'Manual allocation active.':a.shortfall?'Immediate attention required.':a.due.length?'Priority-adjusted allocation active.':'Baseline allocation active.';$('#advisorReasons').innerHTML=a.reasons.map(r=>`<p>${escapeHtml(r)}</p>`).join('');renderBills(a);renderHistory();
}
function renderBills(a){$('#monthlyBillTotal').textContent=money(bills.reduce((s,b)=>s+b.amount*(b.frequency==='biweekly'?26/12:1),0));const list=$('#billList');list.innerHTML='';if(!bills.length){list.innerHTML='<p class="empty">Add your recurring bills to activate priority analysis.</p>';return}bills.slice().sort((a,b)=>(a.dueDay||99)-(b.dueDay||99)).forEach(b=>{const row=$('#billTemplate').content.cloneNode(true),count=a.due.filter(x=>x.id===b.id).length,due=count>0;row.querySelector('.bill-item').style.setProperty('--priority',priorityColors[b.type]);row.querySelector('.bill-name').textContent=b.name;row.querySelector('.bill-meta').textContent=b.frequency==='biweekly'?`Biweekly from ${b.anchorDate} · ${typeLabels[b.type]}`:`Due monthly on day ${b.dueDay} · ${typeLabels[b.type]}`;row.querySelector('.bill-amount').textContent=money(b.amount);row.querySelector('.bill-status').textContent=due?`${count} due this cycle`:'Later';row.querySelector('.bill-status').classList.toggle('due',due);row.querySelector('.remove-bill').addEventListener('click',()=>{bills=bills.filter(x=>x.id!==b.id);save();render()});list.append(row)})}
function update(i,f,v){categories[i][f]=v;if(f==='percent')manualAllocation=true;save();render()}function renderHistory(){$('#history').innerHTML=history.length?history.slice(0,3).map(i=>`<div class="history-item"><span>${escapeHtml(i.source)} · ${i.date}</span><strong>${money(i.amount)}</strong></div>`).join(''):'<p class="empty">No allocations recorded.</p>'}function escapeHtml(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML}
['#paycheck','#payDate','#nextPayDate'].forEach(s=>$(s).addEventListener('input',render));
$('#billFrequency').addEventListener('change',e=>{const bi=e.target.value==='biweekly';$('#monthlyDueField').hidden=bi;$('#biweeklyDueField').hidden=!bi;$('#billDueDay').required=!bi;$('#billAnchorDate').required=bi});
$('#billForm').addEventListener('submit',e=>{e.preventDefault();const frequency=$('#billFrequency').value;bills.push({id:crypto.randomUUID(),name:$('#billName').value.trim(),amount:Number($('#billAmount').value),frequency,dueDay:frequency==='monthly'?Number($('#billDueDay').value):null,anchorDate:frequency==='biweekly'?$('#billAnchorDate').value:null,type:$('#billType').value});e.target.reset();$('#monthlyDueField').hidden=false;$('#biweeklyDueField').hidden=true;$('#billDueDay').required=true;$('#billAnchorDate').required=false;save();render()});
$('#buildPlan').addEventListener('click',()=>{const amount=Number($('#paycheck').value)||0;if(!amount)return $('#paycheck').focus();manualAllocation=false;history.unshift({amount,date:$('#payDate').value,source:$('#paySource').value||'Paycheck'});save();render();document.querySelector('.plan-section').scrollIntoView({behavior:'smooth'})});$('#addCategory').addEventListener('click',()=>{categories.push({name:'New distribution',percent:0,color:'#7090a0'});save();render()});$('#clearHistory').addEventListener('click',()=>{history=[];save();renderHistory()});
const today=new Date();$('#payDate').value=today.toISOString().slice(0,10);const next=new Date(today);next.setDate(next.getDate()+14);$('#nextPayDate').value=next.toISOString().slice(0,10);render();
const mobileQuery=window.matchMedia('(max-width: 600px)'),billForm=$('#billForm'),billToggle=$('#toggleBillForm');
function setBillForm(open){billForm.classList.toggle('mobile-collapsed',mobileQuery.matches&&!open);billToggle.setAttribute('aria-expanded',String(open));billToggle.textContent=open?'Close':'＋ Add bill'}
billToggle.addEventListener('click',()=>setBillForm(billToggle.getAttribute('aria-expanded')!=='true'));
mobileQuery.addEventListener('change',e=>setBillForm(!e.matches));setBillForm(!mobileQuery.matches);
const mobileScreens={pay:[$('#pay-section')],bills:[$('#bills-section')],plan:[$('#plan-section'),$('.bottom-grid')]};
function showMobileScreen(name){if(!mobileQuery.matches)return;Object.values(mobileScreens).flat().forEach(el=>el.classList.remove('mobile-active'));mobileScreens[name].forEach(el=>el.classList.add('mobile-active'));document.querySelectorAll('.mobile-nav button').forEach(button=>button.classList.toggle('active',button.dataset.screen===name));window.scrollTo({top:0,behavior:'instant'})}
document.querySelectorAll('.mobile-nav button').forEach(button=>button.addEventListener('click',()=>showMobileScreen(button.dataset.screen)));
mobileQuery.addEventListener('change',e=>{if(e.matches)showMobileScreen('pay');else Object.values(mobileScreens).flat().forEach(el=>el.classList.remove('mobile-active'))});if(mobileQuery.matches)showMobileScreen('pay');
